server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 登录用户jwt过期时间
    user-secret-key: itcast
    user-ttl: 7200000
    user-token-name: authentication

  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
  minio:
    endpoint: ${sky.minio.endpoint}  # MinIO服务器地址
    accessKey: ${sky.minio.accessKey}           # 访问密钥
    secretKey: ${sky.minio.secretKey}        # 秘密密钥
    # 桶名称已在工具类中固定为 "sky"，此处无需配置
    external-endpoint: ${sky.minio.external-endpoint}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}

